### ISSUE TITLE
Code for multi-source domain adaptation and multi-source domain generalization

### ISSUE THREAD

**Issue by maoshiyun** [VietHoang1512/GLOT#1]
Hello,  can you provide the code for multi-source domain adaptation and multi-source domain generalization?

**Comment by VietHoang1512** [comment]
Hi @maoshiyun, thank you for your interest in our work. Unfortunately I deleted my code on the server and was not able to get back the training file along with the bash script (models and data loader etc are already available in our public repository). However, I found that the training file is hosted in one of my private repositories. Will update them to this repo later this week.

**Comment by VietHoang1512** [comment]
Hi @maoshiyun, I have uploaded the main python file. Please let me know if you have any trouble running our scripts.

**Comment by maoshiyun** [comment]
Thank you for your sharing. There is a line of code “from model_pacs import ModelAggregate” in the file “main_pacs.py”, But the function “ModelAggregate” is not found in the file “main_pacs.py”. Can you share the code of " ModelAggregate"? Thank you very much!

**Comment by VietHoang1512** [comment]
I have updated the code in the newest commit, please reopen the issue if you encounter any problem

**Comment by maoshiyun** [comment]
Thank you for your answer! I have another question, how is the global regularization term used in domain generalization reflected in the code, i.e., can you provide the code for Eq. (13) in the paper?
![image](https://github.com/VietHoang1512/GLOT/assets/121944769/b9707b53-90cc-4b05-a5be-a3d92b47b8fe)

**Comment by VietHoang1512** [comment]
Thank you for your question, each of the term W_d is implemented similar to the [DA code](https://github.com/VietHoang1512/GLOT/blob/main/da-code/train.py#L248) and the [SSL code](https://github.com/VietHoang1512/GLOT/blob/main/ssl-code/svgd/semi.py#L181).
